import {
  attribute,
  autoGeneratedHashKey,
  versionAttribute,
} from '@aws/dynamodb-data-mapper-annotations';

export class DynamoBaseSchema {
  @autoGeneratedHashKey()
  id: string;

  //rangeKey => bug
  @attribute({ defaultProvider: () => new Date() })
  createdAt: Date;

  @attribute({ type: 'Date' })
  deletedAt: Date;

  @versionAttribute()
  version: number;
}
